export const SUPPORTED_TRIGGERS = [
  "WORKITEM_CREATED",
  "WORKITEM_UPDATED",
  "WORKITEM_ASSIGNED",
  "WORKITEM_COMPLETED",
  "WORKITEM_DELETED",
  "COMMENT_ADDED",
  "REPLY_ADDED",
  "MENTION_CREATED",
  "DUE_DATE_REACHED",
  "REMINDER_TIME",
  "SCHEDULE",
  "BOARD_CREATED",
  "PROJECT_UPDATED"
] as const;

export const SUPPORTED_CONDITIONS = [
  "STATUS_EQUALS",
  "STATUS_NOT_EQUALS",
  "PRIORITY_EQUALS",
  "PRIORITY_GREATER_THAN",
  "LABEL_EXISTS",
  "ASSIGNEE_EXISTS",
  "DUE_DATE_BEFORE",
  "DUE_DATE_AFTER",
  "ESTIMATE_GREATER_THAN",
  "WORKSPACE",
  "PROJECT",
  "BOARD"
] as const;

export const SUPPORTED_ACTIONS = [
  "CREATE_NOTIFICATION",
  "ASSIGN_USER",
  "MOVE_WORKITEM",
  "CHANGE_STATUS",
  "CHANGE_PRIORITY",
  "ADD_LABEL",
  "REMOVE_LABEL",
  "CREATE_ACTIVITY",
  "SCHEDULE_REMINDER",
  "CANCEL_REMINDER"
] as const;

export const MAX_EXECUTION_DEPTH = 5;
export const LOOP_PREVENTION_WINDOW_MS = 1000;
export const EXPONENTIAL_BACKOFF_FACTOR = 2;
export const INITIAL_RETRY_DELAY_MS = 1000;
export const MAX_RETRIES = 3;
